service: my-app
frameworkVersion: "3"
provider:
  name: aws
  stage: dev
  region: ap-northeast-1

package:
  patterns:
    - "!**"
    - ".output/server/**"

functions:
  NuxtSsrCore:
    runtime: nodejs22.x
    handler: ".output/server/index.handler"
    url: true #デプロイすると、Lambdaの関数URLが発行される